### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by anantupadhya** [eslam3kl/crtfinder#3]
Hey there.
              I am getting this error whenever I use it 

TypeError: cannot use a string pattern on a bytes-like object

**Comment by abhishekmorla** [comment]
yeah same here : 
Traceback (most recent call last):
  File "/home/abhishek/abhishek/Desktop/new/bug hunting/recon/crtfinder/crtfinder.py", line 113, in <module>
    subdomains = get_data(first_url, second_url)
  File "/home/abhishek/abhishek/Desktop/new/bug hunting/recon/crtfinder/crtfinder.py", line 87, in get_data
    first_subdomain_first_filter = re.findall('(?:<TD>)(.*?)</TD>', first_content) 
  File "/usr/lib/python3.9/re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by ghost** [comment]
I;m getting same error as well. Anybody going to respond?

**Comment by eslam3kl** [comment]
Hello all, 
Please check that you have used the last version of the tool and also with python3 

It works with me
