### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Lu3ky13** [eslam3kl/crtfinder#4]
Hey there.
I am getting this error whenever I use it

[+] Getting the results from crt.sh with these keywords: *.dell.com / dell.*
[+] Start collecting info for: dell
                                                                                                                                         
    subdomains = get_data(first_url, second_url)
  File "/home/roott/Desktop/crtfinder-main/crtfinder.py", line 87, in get_data
    first_subdomain_first_filter = re.findall('(?:<TD>)(.*?)</TD>', first_content) 
  File "/usr/lib/python3.9/re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by 0xVIC** [comment]
Same error:

Traceback (most recent call last):
  File "/opt/crtfinder/crtfinder.py", line 113, in <module>
    subdomains = get_data(first_url, second_url)
  File "/opt/crtfinder/crtfinder.py", line 87, in get_data
    first_subdomain_first_filter = re.findall('(?:<TD>)(.*?)</TD>', first_content) 
  File "/usr/lib/python3.9/re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by eslam3kl** [comment]
Please use python3 with version 1.1
