### ISSUE TITLE
 crtfinder error 

### ISSUE THREAD

**Issue by brupdk** [eslam3kl/crtfinder#5]
hy,
bro your tool error bro 

run python crtfinder.py -u yahoo.com

Traceback (most recent call last):
  File "C:\Users\USER\crtfinder\crtfinder.py", line 113, in <module>
    subdomains = get_data(first_url, second_url)
  File "C:\Users\USER\crtfinder\crtfinder.py", line 87, in get_data
    first_subdomain_first_filter = re.findall('(?:<TD>)(.*?)</TD>', first_content)
  File "C:\python37\lib\re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by GitBib** [comment]
This problem can be solved by #6

**Comment by eslam3kl** [comment]
> This problem can be solved by #6

Thanks for your contribution, merged successfully
